[build]
  publish = "."
  command = "echo 'No build step required'"

[[redirects]]
  from = "/backend/*"
  to = "https://hexlogic-api.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/v2/*"
  to = "https://hexlogic-api.onrender.com/api/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
